name: promethues-radiator-exporter build
on: [push]
jobs:
  build-ubuntu-jammy-debug:
    runs-on: ubuntu-latest
    container: ubuntu:jammy
    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      DEBIAN_FRONTEND: noninteractive
      TZ: Etc/UTC
      PROM_RAD_EXP_CICD: 1
    steps:
      - name: update apt database
        run: apt-get -y update
      - name: update packages
        run: apt-get -y dist-upgrade
      - name: install packages
        run: apt-get -y install curl build-essential pkg-config git libssl-dev
      - name: install rustup
        run: "curl --proto '=https' -sSf https://sh.rustup.rs | sh -s -- -y"
      - name: check out repository code
        uses: actions/checkout@v4
      - name: trust the repository directory
        run: 'git config --global --add safe.directory `pwd`'
      - name: run debug build
        run: '. $HOME/.cargo/env && cargo build --all-targets'
      - name: run debug tests
        run: '. $HOME/.cargo/env && PROM_RAD_EXP_CICD=0 cargo test'
      - name: upload release binary
        uses: actions/upload-artifact@v4
        with:
          name: prometheus-radiator-exporter-debug-ubuntu-jammy
          path: |
            target/debug/prometheus-radiator-exporter
  build-ubuntu-jammy-release:
    runs-on: ubuntu-latest
    container: ubuntu:jammy
    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      DEBIAN_FRONTEND: noninteractive
      TZ: Etc/UTC
      PROM_RAD_EXP_CICD: 1
    steps:
      - name: update apt database
        run: apt-get -y update
      - name: update packages
        run: apt-get -y dist-upgrade
      - name: install packages
        run: apt-get -y install curl build-essential pkg-config git libssl-dev
      - name: install rustup
        run: "curl --proto '=https' -sSf https://sh.rustup.rs | sh -s -- -y"
      - name: check out repository code
        uses: actions/checkout@v4
      - name: trust the repository directory
        run: 'git config --global --add safe.directory `pwd`'
      - name: run release build
        run: '. $HOME/.cargo/env && cargo build --all-targets --release'
      - name: run release tests
        run: '. $HOME/.cargo/env && PROM_RAD_EXP_CICD=0 cargo test --release'
      - name: upload release binary
        uses: actions/upload-artifact@v4
        with:
          name: prometheus-radiator-exporter-release-ubuntu-jammy
          path: |
            target/release/prometheus-radiator-exporter
